#服务器端口
server:
  port: 8501

#数据源配置
spring:
  datasource:
    url: jdbc:mysql://192.168.25.1:3306/seata_order?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: root
    password: snackpub


ribbon:
  ConnectTimeout: 60000 # 连接超时时间(ms)
  ReadTimeout: 60000 # 通信超时时间(ms)


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 60000 # 熔断超时时长：60000ms

# seata配置
seata:
  #registry:
  #  type: nacos
  #  nacos:
  #    server-addr: localhost
  #config:
  #  type: nacos
  #  nacos:
  #    server-addr: localhost
  tx-service-group: snack-seata-order-group
  service:
    grouplist:
      default: 127.0.0.1:8091
    vgroup-mapping:
      snack-seata-order-group: default
    disable-global-transaction: false
  client:
    rm:
      report-success-enable: false
