#服务器端口
server:
  port: 80

#数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seata_storage?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: root
    password: snackpub
#  # Zipkin
#  zipkin:
#    base-url: http://localhost:9411 # Zipkin服务器的地址,向zipkin-server上报调用信息
#  sleuth:
#    sampler:
#      probability: 1.0 #将采样比例设置为1.0，也就是全部都需要。


# WX token
wx.token.grant_type: client_credential
wx.token.appid:
wx.token.secret: