server:
  undertow:
    io-threads: 4
    worker-threads: 20
    buffer-size: 1024
    direct-buffers: true

#spring
spring:
  # Zipkin
  zipkin:
    base-url: http://localhost:9411 # Zipkin服务器的地址,向zipkin-server上报调用信息
  sleuth:
    sampler:
      probability: 1.0 #将采样比例设置为1.0，也就是全部都需要。
  devtools:
    restart:
      log-condition-evaluation-delta: false
    livereload:
      port: 23333

#feign
feign:
  hystrix:
    enabled: true
  #sentinel:
    #enabled: true
  okhttp:
    enabled: true
  httpclient:
    enabled: false

#hystrix配置
hystrix:
  threadpool:
    default:
      coreSize: 300
      maxQueueSize: 1000
      queueSizeRejectionThreshold: 800
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

#ribbon
ribbon:
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  ReadTimeout: 60000
  ConnectTimeout: 60000
  OkToRetryOnAllOperations: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
